"use client";

import { useState } from "react";
import { ArrowRight, CheckCircle2, Upload } from "lucide-react";
import { games, services } from "@/lib/data";
import { createClient } from "@/lib/supabase/client";

export default function Contact(){
  const [name,setName]=useState(""); const [email,setEmail]=useState(""); const [service,setService]=useState(services[0][0]); const [game,setGame]=useState(games[0]); const [deadline,setDeadline]=useState(""); const [details,setDetails]=useState(""); const [sent,setSent]=useState(false); const [error,setError]=useState(""); const [sending,setSending]=useState(false);
  const submit=async(e:React.FormEvent)=>{e.preventDefault();setSending(true);setError("");const {error}=await createClient().from("project_requests").insert({customer_name:name,email:email||null,service,game,deadline:deadline||null,requirements:details});setSending(false);if(error){setError("Request could not be submitted. Please try again shortly.");return}setSent(true);setName("");setEmail("");setDetails("");};
  return <main className="mesh"><section className="section"><div className="container max-w-5xl"><div className="project-head"><div><span className="section-label">Start a project</span><h1 className="section-title">Let&apos;s create your next visual drop.</h1><p className="section-intro mt-5">Share your requirement, deadline and references. The ANYX team will review it before it moves into production.</p></div><div className="project-steps"><span className="is-current">01 Request</span><span>02 Review</span><span>03 Production</span><span>04 Delivery</span></div></div><form className="project-form mt-10" onSubmit={submit}><div className="project-form-main"><label>Your name<input className="input" required value={name} onChange={e=>setName(e.target.value)} placeholder="Your name or team name"/></label><label>Email for project updates<input className="input" type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="you@example.com"/></label><label>What do you need?<select className="input" value={service} onChange={e=>setService(e.target.value)}>{services.map(([x])=><option key={x}>{x}</option>)}</select></label><label>Game / community<select className="input" value={game} onChange={e=>setGame(e.target.value)}>{games.map(x=><option key={x}>{x}</option>)}</select></label><label>Deadline<input className="input" type="date" value={deadline} onChange={e=>setDeadline(e.target.value)}/></label><label className="project-details">Requirements<textarea className="input min-h-40" required value={details} onChange={e=>setDetails(e.target.value)} placeholder="Tell us about your project, preferred style, deliverables and deadline..."/></label></div><div className="project-upload"><Upload size={23}/><h2>Add references</h2><p>Reference uploads are the next step. Your request details are now sent directly to the ANYX review queue.</p><span>Images, video or PDF uploads will be enabled with Supabase Storage.</span></div><div className="project-form-footer"><div>{sent ? <span className="form-success"><CheckCircle2 size={17}/> Request submitted. The ANYX team will review it shortly.</span> : error ? <span className="form-error">{error}</span> : <span>By sending, you start the ANYX review flow.</span>}</div><button disabled={sending} className="btn btn-primary btn-lg">{sending?"Sending request...":"Submit project request"} <ArrowRight size={17}/></button></div></form></div></section></main>;
}
