"use client";

import { useState } from "react";
import { ArrowRight, CheckCircle2, Upload } from "lucide-react";
import { games, services } from "@/lib/data";
import { whatsapp } from "@/lib/utils";

export default function Contact(){
  const [name,setName]=useState(""); const [service,setService]=useState(services[0][0]); const [game,setGame]=useState(games[0]); const [details,setDetails]=useState(""); const [sent,setSent]=useState(false);
  const submit=(e:React.FormEvent)=>{e.preventDefault();setSent(true);window.open(whatsapp(`Hello ANYX Studio, I want to start a project.\nName: ${name}\nService: ${service}\nGame: ${game}\nRequirements: ${details}`),"_blank");};
  return <main className="mesh"><section className="section"><div className="container max-w-5xl"><div className="project-head"><div><span className="section-label">Start a project</span><h1 className="section-title">Let&apos;s create your next visual drop.</h1><p className="section-intro mt-5">Share your requirement, deadline and references. The ANYX team will review it before it moves into production.</p></div><div className="project-steps"><span className="is-current">01 Request</span><span>02 Review</span><span>03 Production</span><span>04 Delivery</span></div></div><form className="project-form mt-10" onSubmit={submit}><div className="project-form-main"><label>Your name<input className="input" required value={name} onChange={e=>setName(e.target.value)} placeholder="Your name or team name"/></label><label>What do you need?<select className="input" value={service} onChange={e=>setService(e.target.value)}>{services.map(([x])=><option key={x}>{x}</option>)}</select></label><label>Game / community<select className="input" value={game} onChange={e=>setGame(e.target.value)}>{games.map(x=><option key={x}>{x}</option>)}</select></label><label>Deadline<input className="input" type="date"/></label><label className="project-details">Requirements<textarea className="input min-h-40" required value={details} onChange={e=>setDetails(e.target.value)} placeholder="Tell us about your project, preferred style, deliverables and deadline..."/></label></div><div className="project-upload"><Upload size={23}/><h2>Add references</h2><p>Upload screenshots, logos, clips or a moodboard. The reference-upload connection can be enabled with Supabase Storage.</p><input type="file" multiple accept="image/*,video/*,.pdf"/><span>Images, video or PDF · up to 10 files</span></div><div className="project-form-footer"><div>{sent ? <span className="form-success"><CheckCircle2 size={17}/> Your request is ready for review.</span> : <span>By sending, you start the ANYX review flow.</span>}</div><button className="btn btn-primary btn-lg">Submit project request <ArrowRight size={17}/></button></div></form></div></section></main>;
}
