import Link from "next/link";
import { ArrowUpRight, Crosshair, Play, Zap } from "lucide-react";
import { games, portfolio, services } from "@/lib/data";

const visualThemes = ["violet", "cyan", "pink", "blue", "amber", "lime"];

export default function Home() {
  return <main className="site-shell overflow-hidden">
    <section className="hero relative flex items-center">
      <div className="hero-orbit hero-orbit-one"/><div className="hero-orbit hero-orbit-two"/><div className="hero-noise"/>
      <div className="container relative z-10 py-14 sm:py-16 lg:py-20"><div className="grid lg:grid-cols-[1.06fr_.94fr] gap-12 lg:gap-8 items-center">
        <div><div className="eyebrow"><Crosshair size={14}/> Gaming creative studio • Online now</div><h1 className="hero-title mt-6">Built for<br/><span className="block text-gradient">the next play.</span></h1><p className="hero-copy mt-6">ANYX Studio creates loud visual systems for esports teams, streamers and gaming brands—from matchday GFX to motion, VFX and ready-to-use digital packs.</p><div className="mt-8 flex flex-col sm:flex-row gap-3"><Link className="btn btn-primary btn-lg group" href="/contact">Start a project <ArrowUpRight size={17} className="transition-transform group-hover:translate-x-0.5 group-hover:-translate-y-0.5"/></Link><Link className="btn btn-secondary btn-lg" href="/portfolio"><Play size={16}/> Watch our work</Link></div><div className="game-ticker mt-9"><span>PLAYING FOR</span>{games.slice(0,5).map(game => <b key={game}>{game}</b>)}</div></div>
        <div className="hero-art-wrap"><div className="hero-art anyx-art"><div className="art-ring art-ring-one"/><div className="art-ring art-ring-two"/><div className="art-panel art-panel-main"><div className="art-kicker">ANYX // CREATIVE UNIT</div><div className="art-word">OWN<br/>THE<br/>LOBBY</div><div className="art-line"/><div className="art-meta">GFX • VFX • MOTION</div></div><div className="art-panel art-panel-small"><span>LVL</span><b>01</b></div><div className="art-panel art-panel-side"><span>EST.<br/>2026</span><Zap size={18}/></div></div></div>
      </div></div>
    </section>
    <section className="section section-tight home-capabilities"><div className="container"><div className="section-heading"><div><span className="section-label">Creative loadout</span><h2 className="section-title">Everything your gaming brand needs to look unstoppable.</h2></div><p className="section-intro">Choose a specialist service or let ANYX build your full visual system from scratch.</p></div><div className="service-grid mt-10">{services.map(([name, description], index) => <Link href="/services" className="service-card" key={name}><div className="service-number">0{index + 1}</div><h3>{name}</h3><p>{description}</p><span className="service-explore">Explore <ArrowUpRight size={16}/></span></Link>)}</div></div></section>
    <section className="section pt-8 home-work"><div className="container"><div className="section-heading"><div><span className="section-label">Selected work</span><h2 className="section-title">Made for the main stage.</h2></div><Link href="/portfolio" className="text-sm font-semibold text-zinc-300 hover:text-white inline-flex items-center gap-2">View all work <ArrowUpRight size={15}/></Link></div><div className="portfolio-grid mt-10">{portfolio.map(([name, category], index) => <Link href="/portfolio" className={`portfolio-card portfolio-${visualThemes[index % visualThemes.length]}`} key={name}><div className="portfolio-art"><div className="portfolio-glow"/><div className="portfolio-shape portfolio-shape-a"/><div className="portfolio-shape portfolio-shape-b"/><div className="portfolio-copy"><span>{category}</span><strong>{name}</strong></div><ArrowUpRight className="portfolio-icon" size={19}/></div></Link>)}</div></div></section>
    <section className="section pt-8 home-cta"><div className="container"><div className="cta-panel"><div><span className="section-label">Queue up a project</span><h2 className="mt-3 text-3xl sm:text-4xl lg:text-5xl font-black tracking-tight">Your next visual drop starts here.</h2></div><Link className="btn btn-primary btn-lg shrink-0" href="/contact">Start a project <ArrowUpRight size={17}/></Link></div></div></section>
  </main>;
}
