"use client";

import Link from "next/link";
import { ArrowRight, Heart, Search, ShoppingBag, SlidersHorizontal, Star, X } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { useSearchParams } from "next/navigation";
import { games, shopCategories } from "@/lib/data";

type Product = { id: string; name: string; description: string | null; category: string; price: number | string; product_type?: "product" | "package" };

export function ShopCatalog({ products }: { products: Product[] }) {
  const searchParams = useSearchParams();
  const [query, setQuery] = useState(""); const [category, setCategory] = useState("All"); const [game, setGame] = useState("All games"); const [sort, setSort] = useState("newest");
  const [saved, setSaved] = useState<string[]>([]); const [cart, setCart] = useState<string[]>([]); const [cartOpen,setCartOpen]=useState(false); const [wishlistReady,setWishlistReady]=useState(false);
  useEffect(() => { if (searchParams.get("cart") === "open") setCartOpen(true); }, [searchParams]);
  useEffect(() => { (async () => { const client = (await import("@/lib/supabase/client")).createClient(); const { data: { user } } = await client.auth.getUser(); if (!user) { setWishlistReady(true); return; } const { data } = await client.from("wishlists").select("product_id").eq("customer_id", user.id); setSaved((data || []).map(item => item.product_id)); setWishlistReady(true); })(); }, []);
  const filtered = useMemo(() => products.filter(p => (category === "All" || p.category.toLowerCase().includes(category.toLowerCase())) && `${p.name} ${p.description || ""}`.toLowerCase().includes(query.toLowerCase())).sort((a,b) => sort === "low" ? Number(a.price)-Number(b.price) : sort === "high" ? Number(b.price)-Number(a.price) : 0), [products, category, query, sort]);
  const toggle = (id:string, list:string[], update:(items:string[])=>void) => update(list.includes(id) ? list.filter(x=>x!==id) : [...list,id]);
  const toggleWishlist = async (id: string) => { const client = (await import("@/lib/supabase/client")).createClient(); const { data: { user } } = await client.auth.getUser(); if (!user) { alert("Please sign in to save wishlist items."); return; } if (saved.includes(id)) { await client.from("wishlists").delete().eq("customer_id", user.id).eq("product_id", id); setSaved(items => items.filter(item => item !== id)); } else { const { error } = await client.from("wishlists").insert({ customer_id: user.id, product_id: id }); if (error) alert(error.message); else setSaved(items => [...items, id]); } };
  const checkout = async () => { const client = (await import("@/lib/supabase/client")).createClient(); const { data: { user } } = await client.auth.getUser(); if (!user) { alert("Please sign in before checkout."); return; } const { error } = await client.rpc("create_anyx_order_with_items", { items: cartProducts.map(product => ({ product_id: product.id, quantity: 1 })) }); if (error) { alert(error.message); return; } setCart([]); setCartOpen(false); alert("Order request created. The ANYX team will confirm delivery shortly."); };
  const cartProducts=products.filter(p=>cart.includes(p.id)); const cartTotal=cartProducts.reduce((sum,p)=>sum+Number(p.price),0);
  return <div className="anyx-catalog-shell">
    <div className="shop-tools"><div className="shop-search"><Search size={18}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search packs, overlays, effects..."/></div><button className="cart-chip" onClick={()=>setCartOpen(true)}><ShoppingBag size={16}/><span>Cart ({cart.length})</span></button></div>
    <div className="shop-filter-row"><div className="filter-label"><SlidersHorizontal size={15}/> Filter</div><div className="filter-scroll"><button className={category === "All" ? "filter-active" : ""} onClick={()=>setCategory("All")}>All</button>{shopCategories.map(x=><button className={category === x ? "filter-active" : ""} onClick={()=>setCategory(x)} key={x}>{x}</button>)}</div><select aria-label="Filter by game" value={game} onChange={e=>setGame(e.target.value)}><option>All games</option>{games.map(x=><option key={x}>{x}</option>)}</select><select aria-label="Sort products" value={sort} onChange={e=>setSort(e.target.value)}><option value="newest">Newest</option><option value="low">Price: Low to high</option><option value="high">Price: High to low</option></select></div>
    <div className="shop-result-line"><span>{filtered.length} assets found</span>{game !== "All games" && <span>Game: {game}</span>}</div>
    <div className="shop-grid">{filtered.map((p,index)=><article className="shop-card" key={p.id}><div className={`shop-cover shop-cover-${index%4}`}><span>{p.product_type === "package" ? "PACKAGE" : p.category}</span><button aria-label={`Save ${p.name}`} className={saved.includes(p.id) ? "shop-icon saved" : "shop-icon"} onClick={()=>toggleWishlist(p.id)} disabled={!wishlistReady}><Heart size={17} fill={saved.includes(p.id) ? "currentColor" : "none"}/></button><div className="shop-cover-graphic"><i/><i/><i/></div><div className="shop-cover-label">ANYX<br/>{p.product_type === "package" ? "CREATIVE PACKAGE" : "ASSET DROP"}</div></div><div className="p-5"><div className="flex justify-between gap-3"><h2>{p.name}</h2><span className="shop-rating"><Star size={13} fill="currentColor"/> 4.9</span></div><p>{p.description || "Gaming creative asset pack."}</p><div className="flex items-center justify-between mt-5"><b>₹{Number(p.price).toLocaleString("en-IN")}</b><div className="flex gap-2"><button aria-label={`Add ${p.name} to cart`} className={cart.includes(p.id) ? "mini-cart added" : "mini-cart"} onClick={()=>toggle(p.id,cart,setCart)}><ShoppingBag size={15}/></button><Link href={`/shop/${p.id}`} className="btn btn-secondary text-xs">View</Link></div></div></div></article>)}</div>
    {!filtered.length && <div className="empty-state"><h2>No assets found.</h2><p>Try another category, search term or game.</p></div>}
    {cartOpen&&<div className="anyx-cart-backdrop" onClick={()=>setCartOpen(false)}><aside className="anyx-cart-drawer" onClick={e=>e.stopPropagation()}><div className="anyx-cart-top"><div><span>YOUR SELECTION</span><h2>Cart ({cart.length})</h2></div><button aria-label="Close cart" onClick={()=>setCartOpen(false)}><X size={20}/></button></div>{cartProducts.length?<div className="anyx-cart-items">{cartProducts.map(p=><div className="anyx-cart-item" key={p.id}><div className="cart-item-image">ANYX</div><div><b>{p.name}</b><span>{p.category}</span><strong>₹{Number(p.price).toLocaleString("en-IN")}</strong></div><button aria-label={`Remove ${p.name}`} onClick={()=>toggle(p.id,cart,setCart)}><X size={16}/></button></div>)}</div>:<div className="anyx-cart-empty"><ShoppingBag size={30}/><h3>Your cart is clear.</h3><p>Add a pack to start your next creative drop.</p></div>}<div className="anyx-cart-bottom"><div><span>SUBTOTAL</span><b>₹{cartTotal.toLocaleString("en-IN")}</b></div><button className="anyx-checkout" disabled={!cart.length} onClick={checkout}>Continue to checkout <ArrowRight size={17}/></button><small>Order request is linked to your customer workspace.</small></div></aside></div>}
  </div>;
}
