"use client";

import { Heart, Play, ShieldCheck, ShoppingBag, Star } from "lucide-react";
import { useEffect, useState } from "react";
import { createClient } from "@/lib/supabase/client";
import { money, whatsapp } from "@/lib/utils";

export default function Product({params}:{params:Promise<{id:string}>}){
  const [id,setId]=useState("");const [product,setProduct]=useState<any>(null);const [items,setItems]=useState<any[]>([]);const [saved,setSaved]=useState(false);const [cart,setCart]=useState(false);
  useEffect(()=>{params.then(async({id})=>{setId(id);const s=createClient();const {data:p}=await s.from("products").select("id,name,description,category,price").eq("id",id).eq("status","published").maybeSingle();setProduct(p);if(p){const {data}=await s.from("product_items").select("id,name").eq("product_id",id).order("sort_order");setItems(data||[]);}})},[params]);
  if(!product)return <main className="mesh min-h-[65vh] grid place-items-center"><span className="muted">Loading asset...</span></main>;
  const buy=()=>window.open(whatsapp(`Hello ANYX Studio, I want to purchase: ${product.name} | Product ID: ${id} | Price: ${money(Number(product.price))}`),"_blank");
  return <main className="mesh"><section className="section"><div className="container grid lg:grid-cols-[1.08fr_.92fr] gap-8"><div><div className="product-preview"><div className="product-preview-grid"/><span>{product.category}</span><strong>ANYX<br/>ASSET<br/>DROP</strong><button className="preview-play" aria-label="Preview asset"><Play size={19} fill="currentColor"/></button></div><div className="preview-strip"><button className="preview-thumb active">01</button><button className="preview-thumb">02</button><button className="preview-thumb">03</button><span>Preview image / video UI</span></div></div><div><span className="section-label">Digital asset</span><h1 className="product-title">{product.name}</h1><div className="product-rating"><Star size={16} fill="currentColor"/> <b>4.9</b> <span>(24 reviews)</span></div><p className="muted mt-6 leading-7">{product.description || "A polished ANYX Studio digital creative asset pack."}</p><div className="product-price">{money(Number(product.price))}</div><div className="product-actions"><button className={cart ? "btn btn-primary flex-1" : "btn btn-primary flex-1"} onClick={()=>setCart(!cart)}><ShoppingBag size={17}/>{cart ? "Added to cart" : "Add to cart"}</button><button className="btn btn-secondary flex-1" onClick={buy}>Buy now</button><button className={saved ? "product-heart saved" : "product-heart"} aria-label="Add to wishlist" onClick={()=>setSaved(!saved)}><Heart size={19} fill={saved?"currentColor":"none"}/></button></div><div className="product-assurance"><ShieldCheck size={20}/><span><b>Instant delivery</b><br/>Files unlock after your order is confirmed.</span></div><div className="product-includes"><h2>What&apos;s included</h2>{items.length?items.map(item=><div key={item.id}>{item.name}</div>):<div>Asset files and usage guide</div>}</div><div className="review-box"><div><b>Community reviews</b><p>Verified customer rating and review UI.</p></div><div className="review-score">4.9 <Star size={15} fill="currentColor"/></div></div></div></div></section></main>;
}
